# Generated by Django 5.2.1 on 2025-05-18 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy_name', models.CharField(choices=[('Завод', 'Завод'), ('Розничная сеть', 'Розничная сеть'), ('ИП', 'ИП')], max_length=20, verbose_name='Тип звена иерархии')),
                ('title', models.CharField(max_length=10, verbose_name='Название')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Электронная почта')),
                ('country', models.CharField(default='Россия', max_length=15, verbose_name='Страна')),
                ('city', models.CharField(max_length=15, verbose_name='Город')),
                ('street', models.CharField(max_length=20, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('product_name', models.CharField(max_length=20, verbose_name='Наименование товара')),
                ('product_model', models.CharField(max_length=15, verbose_name='Модель товара')),
                ('product_date', models.DateField(verbose_name='Дата выхода на рынок')),
                ('debt_for_supplier', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Задолженность перед поставщиком')),
                ('data_create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_store.linknetwork', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'звено продажи',
                'verbose_name_plural': 'звенья продажи',
                'ordering': ['title'],
            },
        ),
    ]
