# Generated by Django 5.2.1 on 2025-05-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linknetwork',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
