# Generated by Django 5.2.1 on 2025-05-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0002_alter_linknetwork_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linknetwork',
            name='product_name',
            field=models.CharField(max_length=50, verbose_name='Наименование товара'),
        ),
    ]
